module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
modules:
  Crypto.Cipher.Salsa20.LE:
    filename: src/Crypto/Cipher/Salsa20/LE.hs
  Tests:
    filename: test/Tests.hs
  Crypto.Cipher.Salsa20:
    filename: src/Crypto/Cipher/Salsa20.hs
  Benchmarks:
    filename: bench/Benchmarks.hs
version: 1
extra-packages: ''
ghc-args: []
