module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  Tests:
    filename: test/Tests.hs
  Crypto.Cipher.Salsa20:
    filename: src/Crypto/Cipher/Salsa20.hs
  Benchmarks:
    filename: bench/Benchmarks.hs
version: 1
ghc-args: []
