module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  Crypto.Cipher.Salsa20:
    filename: src/Crypto/Cipher/Salsa20.hs
  UnitTests:
    filename: tests/UnitTests.hs
  Benchmarks:
    filename: tests/Benchmarks.hs
version: 1
ghc-args: []
